### ISSUE TITLE
API – impl mismatch: partitioning_strategy vs. partition_strategy

### ISSUE THREAD

**Issue by ePaul** [zalando/nakadi#258]
The [OpenAPI definition](https://github.com/zalando/nakadi/blob/34bac250287e908bebcea767aa94b284cf8f90ae/api/nakadi-event-bus-api.yaml#L1194) contains this in the `EventType` definition:

```yaml
  EventType:
    description: An event type defines the schema and its runtime properties.
    properties:
        ...
      partitioning_key_fields:
        type: array
        items:
          type: string
        description: |
          Required when 'partition_resolution_strategy' is set to 'hash'. Must be absent otherwise.
          Indicates the fields used for evaluatiion the partition of Events of this type.
          If set it MUST be a valid required field as defined in the schema.
```

Sending the following definition with PUT (for an existing event type) to the Sandbox Nakadi resulted in an error message:

```json
{
  "name": "wholesale.warehouse-change-event",
  "owning_application": "wholesale.warehouse-allocation",
  "category": "data",
  "enrichment_strategies": ["metadata_enrichment"],
  "partitioning_strategy": "hash",
  "partition_key_fields": [ "code" ],
  "schema": {
    "type" : "json_schema",
    "schema": "{\"type\":\"object\",\"properties\":{\"self\":{\"type\":\"string\"},\"code\":{\"type\":\"string\"},\"name\":{\"type\":\"string\"},\"address\":{\"type\":\"object\",\"properties\":{\"name\":{\"type\":\"string\"},\"street\":{\"type\":\"string\"},\"city\":{\"type\":\"string\"},\"zip\":{\"type\":\"string\"},\"country\":{\"type\":\"string\"},\"additional\":{\"type\":\"string\"}},\"required\":[\"name\",\"street\",\"city\",\"zip\",\"country\"]},\"is_allowed_for_shipping\":{\"type\":\"boolean\"},\"is_allowed_for_purchase_order\":{\"type\":\"boolean\"},\"legacy_warehouse_code\":{\"type\":\"string\"}},\"required\":[\"name\",\"address\",\"is_allowed_for_purchase_order\",\"is_allowed_for_shipping\"]}"
  }
}
```
Error:

```json
{
  "type": "http://httpstatus.es/400",
  "title": "Bad Request",
  "status": 400,
  "detail": "Unrecognized field \"partitioning_key_fields\" (class de.zalando.aruha.nakadi.domain.EventType), not marked as ignorable (8 known properties: \"schema\", \"default_statistic\", \"partition_strategy\", \"name\", \"owning_application\", \"category\", \"enrichment_strategies\", \"partition_key_fields\"])\n at [Source: java.io.PushbackInputStream@145b0c0d; line: 7, column: 31] (through reference chain: de.zalando.aruha.nakadi.domain.EventType[\"partitioning_key_fields\"])"
}
```

It looks like the implementation understands only `partition_key_fields`, not the advertised `partitioning_key_fields`. (Sending the event type with `partition_key_fields` works.)
