### ISSUE TITLE
API – impl mismatch: upper case vs. lower case

### ISSUE THREAD

**Issue by ePaul** [zalando/nakadi#259]
The BatchItemResponse definition [in the OpenAPI definition](https://github.com/zalando/nakadi/blob/34bac250287e908bebcea767aa94b284cf8f90ae/api/nakadi-event-bus-api.yaml#L1277) looks like this:

```yaml
  BatchItemResponse:
    description: |
      A status corresponding to one individual Event's publishing attempt.
    properties:
      eid:
        type: string
        format: uuid
        description: |
          eid of the corresponding item. Will be absent if missing on the incoming Event.
      publishing_status:
        type: string
        enum:
          - SUBMITTED
          - FAILED
          - ABORTED
        description: |
          Indicator of the submission of the Event within a Batch.
          - SUBMITTED indicates successful submission, including commit on he underlying broker.
          - FAILED indicates the message submission was not possible and can be resubmitted if so desired.
          - ABORTED indicates that the submission of this item was not attempted any further due to a failure
            on another item in the batch.
      step:
        type: string
        enum:
          - NONE
          - VALIDATING
          - ENRICHING
          - PARTITIONING
          - PUBLISHING
        description: |
          Indicator of the step in the pulbishing process this Event reached.
          In Items that FAILED means the step of the failure.
          - NONE indicates that nothing was yet attempted for the publishing of this Event. Should be present
            only in the case of aborting the publishing during the validation of another (previous) Event.
          - VALIDATING, ENRICHING, PARTITIONING and PUBLISHING indicate all the corresponding steps of the
            publishing process.
      detail:
        type: string
        description: |
          Human readable information about the failure on this item. Items that are not SUBMITTED should have
          a description.
    required:
      - publishing_status
```

The messages which are actually returned from a running Nakadi have those `publishing_status` and `step` values instead in lower case (i.e. `submitted`, `failed`, `aborted` for the status, `none`, `validating`, `enriching`, `partitioning`, `publishing` for steps).

API definition and implementation should be brought into agreement, either by adapting the API or by adapting the implementation.
